#!/usr/bin/env bash

set -e
shopt -s extglob

AOC_YEAR=2021
AOC_LANG=hs

usage () {
    echo 'usage: ./aoc [-l LANG]  <DAY> [YEAR]' >&2
    echo '           | test-all [YEAR]' >&2
    echo ' -l LANG -- language to use, default hs' >&2
    echo '            choices: hs, asm, nix' >&2
    exit 1
}

day () {
    if ! [ -z "$2" ]; then
        AOC_YEAR="$2"
    fi
    DAY="$1"
    echo "Setting up day ${DAY} (${AOC_YEAR}, ${AOC_LANG})";
    mkdir -p "${AOC_YEAR}/day${DAY}"
    if ! [ -e "${AOC_YEAR}/day${DAY}/run.${AOC_LANG}" ]; then
        cp "template/run.${AOC_LANG}" "${AOC_YEAR}/day${DAY}/"
    fi
    cd "${AOC_YEAR}/day${DAY}"

    echo "Compile/run with:"
    case $AOC_LANG in
        asm) echo "  nasm -felf64 run.asm && ld -o run run.o && time ./run < input.txt" ;;
        hs) echo "  ghc -O2 run.hs && time ./run" ;;
        nix) echo "  time nix-eval ./run.nix" ;;
        *) usage ;;
    esac

    exec nix develop ".#langs.${AOC_LANG}"
}

while true; do
    case $1 in
        -l) shift; AOC_LANG="$1"; shift;;
        +([0-9])) day $1 $2;;
        *) usage;;
    esac
done
