#!/usr/bin/env bash

set -e
shopt -s extglob

YEAR=2020

usage () {
    echo 'usage: ./aoc DAY' >&2
    exit 1
}

day () {
    echo "Setting up day $1 ($YEAR)";
    mkdir -p "$YEAR/day$1"
    if ! [ -e "$YEAR/day$1/run.hs" ]; then
        cp "template/run.hs" "$YEAR/day$1/"
    fi
    cd "$YEAR/day$1"
    exec nix-shell ../../shell.nix --run "$SHELL"
}

testAll () {
    YEAR=$YEAR nix-shell --run "./test-runner"
}

case $1 in
    +([0-9])) day $1;;
    test-all) testAll;;
    *) usage;;
esac
