#!/usr/bin/env bash

set -e

if [ -z "$1" ]; then
    YEAR=2020
else
    YEAR="$1"
fi

status () {
    echo "===" "$1" "$2" "($3)" "==="
}

for d in $(ls $YEAR | sort -V); do
    status "COMPILING" "$d" "$YEAR"
    cd "$YEAR/$d"
    ghc -O2 run.hs
    status "RUNNING" "$d" "$YEAR"
    time ./run
    status "ALL DONE" "$d" "$YEAR"
    cd -
done
